name: 'actions-setup-cmake'
description: 'Setup the cmake build generator'
inputs:
  cmake-version:
    description: 'The version of cmake to setup. E.g. 3.14.0'
    default: ''
  github-api-token:
    description: 'GitHub token to use when retrieving version info'
    default: '${{ github.token }}'
  use-32bit:
    description: 'Force using 32 bit version of cmake, instead of looking for 64 bit version'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
