on:
  pull_request:
    branches: [master]

jobs:
  latest_version:
    runs-on: ${{ matrix.os }}
    name: Test latest version
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup cmake
      uses: ./
      id: setup
      with:
        cmake-version: 'latest'

    - name: Run cmake --version
      shell: bash
      run: |
        VERSION=`cmake --version`
        echo $VERSION
