on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  action_tests:
    runs-on: ${{ matrix.os }}
    name: Action Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cmake_ver: ['', '3.19.3', '3.15.1', '2.8']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup cmake
      uses: ./
      id: setup
      with:
        cmake-version: ${{ matrix.cmake_ver }}

    - name: Run cmake --version
      shell: bash
      if: matrix.cmake_ver != ''
      run: |
        VERSION=`cmake --version`
        echo $VERSION
        [[ "$VERSION" =~ "${{ matrix.cmake_ver }}" ]]

    - name: Run cmake --version
      # [[ "$VERSION" =~ "" ]] does not work as expected on macos, so don't
      # do the test when using the latest cmake version
      shell: bash
      if: matrix.cmake_ver == ''
      run: |
        VERSION=`cmake --version`
        echo $VERSION

  unit_tests:
    runs-on: ${{ matrix.os }}
    name: Unit Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install node dependencies
      run: npm install

    - name: Check `npm run format` has been run
      run: |
        npm run format
        git diff --quiet src/ __tests__/

    - name: Check `npm run package` has been run
      run: |
        npm run package
        git diff --quiet dist/

    - name: Run tests
      run: npm test
