on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  action_tests:
    runs-on: ${{ matrix.os }}
    name: Action Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cmake_ver: [3.15.1, 2.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup cmake
      uses: ./
      id: setup
      with:
        cmake-version: ${{ matrix.cmake_ver }}

    - name: Run cmake --version
      shell: bash
      run: |
        VERSION=`cmake --version`
        echo $VERSION
        [[ "$VERSION" =~ "${{ matrix.cmake_ver }}" ]]

  unit_tests:
    runs-on: ${{ matrix.os }}
    name: Unit Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install
      run: npm install

    - name: Format
      run: |
        npm run format
        git diff --quiet src/ __tests__/

    - name: Run tests
      run: npm test
